### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sinder38** [tengattack/grafana-jsform-panel#3]
![Screenshot from 2021-05-05 02-37-08](https://user-images.githubusercontent.com/49784830/117082457-fdab9e00-ad4a-11eb-8690-bdb91a04d703.png)
I think i did something wrong. I didn't make sending function, for the test i wanted it to log "success".

**Comment by sinder38** [comment]
btw my goal is to send received data to the database or via mqtt

**Comment by tengattack** [comment]
It using restful API to send or receice data, you have to configured API in panel settings at form action field.

**Comment by sinder38** [comment]
how to configure it?

**Comment by tengattack** [comment]
It just like postman, you have an API, configure the API to form action field in panel settings.

**Comment by sinder38** [comment]
> It just like postman, you have an API, configure the API to form action field in panel settings.

so my api supposed to read json data from web page?

**Comment by sinder38** [comment]
![Screenshot from 2021-05-06 01-08-47](https://user-images.githubusercontent.com/49784830/117215915-a1f31a80-ae07-11eb-9e16-beee500c8a2e.png)

I copied function from example and changed address in it. Also i filled address of my server + port in form action(I changed it for the showcase). To be honest I don't understand what I'm doing.

**Comment by sinder38** [comment]
creating a program that reads the page data isn't a problem

**Comment by tengattack** [comment]
ummmm, I will tell you what this plugin does at first.

As we know, Grafana usually is used to display data from various data sources (readonly). This plugin makes it's possible using grafana to "wirte" data to data sources (via web browser API http request).
Does the plugin meet your requirements?

Then, this plugin can create custom from json schema on panel. It generates from, after that, grafana viewer (people) using the form to make request payload. After click the submit button, the plugin tells the web browser generates request payload and send it to the server (from action). We can "write" or "update" data in data sources via the API.

And finally, the plugin display some updated message from the API response, and refresh other panel to display latest data as you configured.

**Comment by sinder38** [comment]
It perfect. The problem I don't understand how to make it work

**Comment by sinder38** [comment]
Example in grafana will be useful. Btw grafana is also on my server.

**Comment by tengattack** [comment]
> It perfect. The problem is I don't understand how to make it work

Could you create a public API? And tell me what's the param and the response, I will help you to create a simple jsform panel.

**Comment by sinder38** [comment]
Ok

**Comment by sinder38** [comment]
here is the url: http://472109-cj61305.tmweb.ru:5003

this python code sends data to the api:
from requests import put
put('http://472109-cj61305.tmweb.ru:5003/file1', data={'data': '12345'}).json()

after that received data can be accessed on the same page + filename(http://472109-cj61305.tmweb.ru:5003/file1)

**Comment by sinder38** [comment]
i can send you the api code if you need it.

**Comment by tengattack** [comment]
Could you change to post method? instead of PUT method which is this panel not supported.

**Comment by sinder38** [comment]
Restarted with post instead of put

**Comment by tengattack** [comment]
Successfully POST, but has no CORS headers, could you add the CORS headers like which I post before?

```
$ curl -XPOST http://472109-cj61305.tmweb.ru:5003/file1 -H "Origin: http://test.com" -d 'data=12345' -v   teng@test01
* About to connect() to 472109-cj61305.tmweb.ru port 5003 (#0)
*   Trying 94.228.112.12...
* Connected to 472109-cj61305.tmweb.ru (94.228.112.12) port 5003 (#0)
> POST /file1 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 472109-cj61305.tmweb.ru:5003
> Accept: */*
> Origin: http://test.com
> Content-Length: 10
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 10 out of 10 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Type: application/json
< Content-Length: 19
< Server: Werkzeug/1.0.1 Python/3.6.9
< Date: Fri, 07 May 2021 06:26:49 GMT
<
{"file1": "12345"}
* Closing connection 0
*
```

**Comment by sinder38** [comment]
i guess its OK now( i added CORS headers)

**Comment by tengattack** [comment]
@sinder38 it shows HTTP/1.0 500 INTERNAL SERVER ERROR

```
$ curl -XPOST http://472109-cj61305.tmweb.ru:5003/file1 -H "Origin: http://test.com" -d 'data=12345' -v
```

**Comment by sinder38** [comment]
I dunno what is causing that. I should check my code

**Comment by sinder38** [comment]
I made a stupid mistake, Its fixed now

**Comment by sinder38** [comment]
@tengattack I made a stupid mistake, Its fixed now

**Comment by tengattack** [comment]
@sinder38 
```
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Headers: Accept, Accept-Encoding, Accept-Language, Connection, Content-Type, Content-Length, Cookie, Origin, Referer, User-Agent
```

With `Access-Control-Allow-Credentials: true`, `Access-Control-Allow-Origin` should be same as http request headers' 'Origin', like `ngx.header['Access-Control-Allow-Origin'] = ngx.var.http_origin`, instead of `*`.

**Comment by tengattack** [comment]
You can try this:

Json Schema:
```json
{
  "title": "Person",
  "type": "object",
  "required": [
    "file1"
  ],
  "properties": {
    "file1": {
      "type": "string",
      "description": "First and Last name",
      "minLength": 4,
      "default": "Jeremy Dorn"
    }
  }
}
```

Other settings:
![image](https://user-images.githubusercontent.com/1846356/117527992-8b64e300-b002-11eb-8976-3fa8ca0fee8c.png)

And submit it, it will show like this:
![image](https://user-images.githubusercontent.com/1846356/117528005-9f104980-b002-11eb-9b41-d781f4afbc49.png)

It seems your server still can't read the data from the web browser, could you check it?

What's more, the response json, should have a `success: true` to indicates the request success. For example:

```json
{"success": true, "file1": "12345"}
```

**Comment by sinder38** [comment]
i've added `success: true` in get method, so http://472109-cj61305.tmweb.ru:5003/file1 returns `{"success": true, "file1": "12345"}` after curl -XPOST http://127.0.0.1:5003/file1 -H "Origin: http://test.com" -d 'data=12345' -v.

But the panel is still complaining about received request

**Comment by sinder38** [comment]
i want to know how does panel message look like to the api

**Comment by sinder38** [comment]
i fixed it


> i've added `success: true` in get method, so http://472109-cj61305.tmweb.ru:5003/file1 returns `{"success": true, "file1": "12345"}` after curl -XPOST http://127.0.0.1:5003/file1 -H "Origin: http://test.com" -d 'data=12345' -v.
> 
> But the panel is still complaining about received request

nvm i fixed it
